server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_account?currentSchema=user_account_schema
    username: app_user
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true